import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        self.title_style = ParagraphStyle(
            "CustomTitle",
            parent=self.styles["Title"],
            fontSize=24,
            textColor=colors.HexColor("#1a237e"),
            spaceAfter=12,
            alignment=TA_CENTER,
        )
        self.h1_style = ParagraphStyle(
            "CustomH1",
            parent=self.styles["Heading1"],
            fontSize=16,
            textColor=colors.HexColor("#283593"),
            spaceBefore=16,
            spaceAfter=8,
            borderPad=4,
        )
        self.h2_style = ParagraphStyle(
            "CustomH2",
            parent=self.styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#37474f"),
            spaceBefore=10,
            spaceAfter=6,
        )
        self.body_style = ParagraphStyle(
            "CustomBody",
            parent=self.styles["Normal"],
            fontSize=10,
            leading=14,
            spaceAfter=6,
        )

    def generate(self, results: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=0.75 * inch,
        )
        story = []

        # Title Page
        story.append(Spacer(1, 1.5 * inch))
        story.append(Paragraph("AI-Powered Product Strategy Report", self.title_style))
        story.append(Spacer(1, 0.2 * inch))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a237e")))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Generated by AI Product Strategy Assistant", self.styles["Normal"]))
        story.append(PageBreak())

        sections = [
            ("Executive Summary", "executive_report"),
            ("Customer Insights Report", "customer_feedback"),
            ("Sales Analysis", "sales_analysis"),
            ("Competitor & Market Analysis", "competitor_analysis"),
            ("SWOT Analysis", "swot_analysis"),
            ("Feature Prioritization Recommendations", "feature_prioritization"),
        ]

        for title, key in sections:
            content = results.get(key, "")
            if not content:
                continue
            story.append(Paragraph(title, self.h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#90caf9")))
            story.append(Spacer(1, 0.1 * inch))
            self._add_markdown_content(story, content)
            story.append(PageBreak())

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    def _add_markdown_content(self, story, text: str):
        for line in text.split("\n"):
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 0.05 * inch))
                continue
            if stripped.startswith("## "):
                story.append(Paragraph(stripped[3:], self.h1_style))
            elif stripped.startswith("### "):
                story.append(Paragraph(stripped[4:], self.h2_style))
            elif stripped.startswith("**") and stripped.endswith("**"):
                story.append(Paragraph(f"<b>{stripped[2:-2]}</b>", self.body_style))
            elif stripped.startswith("- ") or stripped.startswith("• "):
                bullet_text = stripped[2:].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(f"&bull; {bullet_text}", self.body_style))
            elif stripped.startswith("#"):
                story.append(Paragraph(stripped.lstrip("# "), self.h2_style))
            else:
                safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, self.body_style))
